name: almohandis_pos
description: "Al-Mohandis Electrical Tools POS Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  signals_flutter: any
  realm: any
  easy_localization: ^3.0.7
  go_router: any
  responsive_framework: any
  printing: any
  pdf: any
  fl_chart: any
  crypto: any
  http: any
  flutter_barcode_scanner: any
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  shared_preferences: any
  intl: any
  get_it: ^9.2.1
  file_picker: ^8.1.3
  path_provider: ^2.1.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
