name: almohandis_pos
description: "Al-Mohandis Electrical Tools POS Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  signals_flutter: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.7
  go_router: any
  responsive_framework: any
  printing: any
  pdf: any
  fl_chart: any
  crypto: any
  http: any
  flutter_barcode_scanner_plus: ^3.0.8
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  shared_preferences: any
  intl: any
  get_it: ^9.2.1
  file_picker: ^8.1.3
  path_provider: ^2.1.3
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: any
  inno_bundle: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/logo.jpg"

inno_bundle:
  id: 0C1B0360-F22B-4521-BD33-C6F36476FAD1
  name: Al-Mohandis POS
  publisher: Al-Mohandis
  installer_icon: windows/runner/resources/app_icon.ico
  languages:
    - english
    - arabic

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
