import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../features/inventory/domain/entities/product_entity.dart';
import '../../../../features/inventory/domain/repositories/product_repository.dart';
import '../../../../features/customers/domain/entities/customer_entity.dart';
import '../../../../features/customers/domain/repositories/customer_repository.dart';
import '../../../../features/suppliers/domain/entities/supplier_entity.dart';
import '../../../../features/suppliers/domain/repositories/supplier_repository.dart';
import '../../../../features/pos/domain/entities/sale_entity.dart';
import '../../../../features/pos/domain/repositories/sale_repository.dart';
import '../../../../services/activity_log_service.dart';

// States
abstract class ReturnsState {}

class ReturnsInitial extends ReturnsState {}

class ReturnsLoading extends ReturnsState {}

class ReturnsLoaded extends ReturnsState {
  final List<ProductEntity> products;
  final List<CustomerEntity> customers;
  final List<SupplierEntity> suppliers;

  ReturnsLoaded({
    required this.products,
    required this.customers,
    required this.suppliers,
  });
}

class ReturnsSuccess extends ReturnsState {
  final String message;
  ReturnsSuccess(this.message);
}

class ReturnsError extends ReturnsState {
  final String message;
  ReturnsError(this.message);
}

// Cubit
class ReturnsCubit extends Cubit<ReturnsState> {
  final ProductRepository productRepository;
  final CustomerRepository customerRepository;
  final SupplierRepository supplierRepository;
  final SaleRepository saleRepository;
  final ActivityLogService activityLogService;

  ReturnsCubit({
    required this.productRepository,
    required this.customerRepository,
    required this.supplierRepository,
    required this.saleRepository,
    required this.activityLogService,
  }) : super(ReturnsInitial());

  Future<void> loadData() async {
    emit(ReturnsLoading());
    try {
      final products = await productRepository.getProducts();
      final customers = await customerRepository.getCustomers();
      final suppliers = await supplierRepository.getSuppliers();
      emit(ReturnsLoaded(
        products: products,
        customers: customers,
        suppliers: suppliers,
      ));
    } catch (e) {
      emit(ReturnsError(e.toString()));
    }
  }

  Future<void> processSalesReturn({
    required String productId,
    required String customerId,
    required int qty,
    required double price,
    required bool isRefundCash,
    String? note,
    required String cashierUsername,
  }) async {
    emit(ReturnsLoading());
    try {
      final product = await productRepository.getProductById(productId);
      if (product == null) throw Exception('Product not found');

      final customer = await customerRepository.getCustomerById(customerId);
      if (customer == null) throw Exception('Customer not found');

      final totalReturnAmount = qty * price;

      // 1. Increase inventory stock
      await productRepository.updateStock(productId, qty);

      // 2. Adjust customer balance and purchases
      final debtReduction = isRefundCash ? 0.0 : totalReturnAmount;
      await customerRepository.updatePurchases(customerId, -totalReturnAmount, -debtReduction);

      // 3. Create negative invoice transaction in Sale DB to update sales history & reports
      final serial = await saleRepository.getNextInvoiceNumber();
      final returnSale = SaleEntity(
        id: '', // Generated by database mapper
        invoiceNumber: 'RET-$serial',
        createdAt: DateTime.now(),
        items: [
          SaleItemEntity(
            productId: productId,
            productName: product.name,
            barcode: product.barcode,
            qty: -qty, // Negative quantity
            unitPrice: price,
            totalPrice: -totalReturnAmount,
            priceLevel: customer.priceLevel,
          )
        ],
        subtotal: -totalReturnAmount,
        discount: 0.0,
        tax: 0.0,
        total: -totalReturnAmount,
        paymentMethod: isRefundCash ? 'cash' : 'balance_deduction',
        customerId: customerId,
        cashierId: cashierUsername,
        note: note ?? 'Sales Return',
        amountPaid: isRefundCash ? -totalReturnAmount : 0.0,
        amountRemaining: isRefundCash ? 0.0 : -totalReturnAmount,
      );
      await saleRepository.saveSale(returnSale);

      // 4. Log the action
      activityLogService.log(
        action: 'sales_return',
        category: 'returns',
        description: 'Sales return: Returned $qty x ${product.name} for customer ${customer.name}. Total refund: $totalReturnAmount EGP',
        userId: cashierUsername,
        referenceId: productId,
      );

      emit(ReturnsSuccess('return_success'));
      await loadData();
    } catch (e) {
      emit(ReturnsError(e.toString()));
    }
  }

  Future<void> processPurchaseReturn({
    required String productId,
    required String supplierId,
    required int qty,
    required double price,
    required bool isReceivedCash,
    String? note,
    required String cashierUsername,
  }) async {
    emit(ReturnsLoading());
    try {
      final product = await productRepository.getProductById(productId);
      if (product == null) throw Exception('Product not found');

      final supplier = await supplierRepository.getSupplierById(supplierId);
      if (supplier == null) throw Exception('Supplier not found');

      final totalReturnAmount = qty * price;

      // 1. Decrease inventory stock (returning it to supplier)
      await productRepository.updateStock(productId, -qty);

      // 2. Adjust supplier balance and purchases
      final balanceReduction = isReceivedCash ? 0.0 : totalReturnAmount;
      await supplierRepository.updateOrders(supplierId, -totalReturnAmount, -balanceReduction);

      // 3. Log the action
      activityLogService.log(
        action: 'purchase_return',
        category: 'returns',
        description: 'Purchase return: Returned $qty x ${product.name} to supplier ${supplier.name}. Total: $totalReturnAmount EGP',
        userId: cashierUsername,
        referenceId: productId,
      );

      emit(ReturnsSuccess('return_success'));
      await loadData();
    } catch (e) {
      emit(ReturnsError(e.toString()));
    }
  }
}
